//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MADDPeriodicTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public int ID { get; set; }
        public string Element_Abbreviation { get; set; }
        public string Element_Name { get; set; }
        public decimal Atomic_Weight { get; set; }
    }
}
