//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MADDPeriodicTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PeriodicTableEntities : DbContext
    {
        public PeriodicTableEntities()
            : base("name=PeriodicTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Compound> Compounds { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<UserProgress> UserProgresses { get; set; }
    
        public virtual ObjectResult<sp_s_Com_Result> sp_s_Com()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_s_Com_Result>("sp_s_Com");
        }
    
        public virtual ObjectResult<sp_s_Ele_Result> sp_s_Ele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_s_Ele_Result>("sp_s_Ele");
        }
    }
}
